apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: https://github.com/msakhawat/FlaskApp.git
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2020-10-13T07:24:52Z
    labels:
      app: webapp-name
      app.kubernetes.io/component: webapp-name
      app.kubernetes.io/instance: webapp-name
      app.kubernetes.io/part-of: webapp-appname
    name: webapp-name
    namespace: webproject
    resourceVersion: "299588731"
    selfLink: /apis/build.openshift.io/v1/namespaces/webproject/buildconfigs/webapp-name
    uid: b24ed816-7b98-4391-bac3-f615e9a6830f
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: webapp-name:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /
      git:
        uri: https://github.com/msakhawat/FlaskApp.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - generic:
        secretReference:
          name: webapp-name-generic-webhook-secret
      type: Generic
    - github:
        secretReference:
          name: webapp-name-github-webhook-secret
      type: GitHub
    - type: ConfigChange
  status:
    lastVersion: 1
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
