apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: Build
  metadata:
    annotations:
      openshift.io/build-config.name: webapp-name
      openshift.io/build.number: "1"
      openshift.io/build.pod-name: webapp-name-1-build
    creationTimestamp: 2020-10-13T07:24:52Z
    labels:
      app: webapp-name
      app.kubernetes.io/component: webapp-name
      app.kubernetes.io/instance: webapp-name
      app.kubernetes.io/part-of: webapp-appname
      buildconfig: webapp-name
      openshift.io/build-config.name: webapp-name
      openshift.io/build.start-policy: Serial
    name: webapp-name-1
    namespace: webproject
    ownerReferences:
    - apiVersion: build.openshift.io/v1
      controller: true
      kind: BuildConfig
      name: webapp-name
      uid: b24ed816-7b98-4391-bac3-f615e9a6830f
    resourceVersion: "299590242"
    selfLink: /apis/build.openshift.io/v1/namespaces/webproject/builds/webapp-name-1
    uid: 51e7d656-35d7-4680-bdc1-500efbd4619d
  spec:
    nodeSelector: null
    output:
      pushSecret:
        name: builder-dockercfg-w59q8
      to:
        kind: ImageStreamTag
        name: webapp-name:latest
    postCommit: {}
    resources: {}
    revision:
      git:
        author:
          email: m.sakhawat.ali@gmail.com
          name: Sakhawat
        commit: e939cb0a7a5d5fc9350e1b3170addc202fcc39c7
        committer:
          email: m.sakhawat.ali@gmail.com
          name: Sakhawat
        message: add openshift stuff
      type: Git
    serviceAccount: builder
    source:
      contextDir: /
      git:
        uri: https://github.com/msakhawat/FlaskApp.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    triggeredBy:
    - message: Build configuration change
  status:
    completionTimestamp: 2020-10-13T07:25:50Z
    conditions:
    - lastTransitionTime: 2020-10-13T07:24:53Z
      lastUpdateTime: 2020-10-13T07:24:53Z
      status: "False"
      type: New
    - lastTransitionTime: 2020-10-13T07:24:56Z
      lastUpdateTime: 2020-10-13T07:24:56Z
      status: "False"
      type: Pending
    - lastTransitionTime: 2020-10-13T07:25:50Z
      lastUpdateTime: 2020-10-13T07:25:50Z
      status: "False"
      type: Running
    - lastTransitionTime: 2020-10-13T07:25:50Z
      lastUpdateTime: 2020-10-13T07:25:50Z
      status: "True"
      type: Complete
    config:
      kind: BuildConfig
      name: webapp-name
      namespace: webproject
    duration: 57000000000
    output:
      to:
        imageDigest: sha256:616a75aca2298f3361558b4d8708093716e8289f3d4cfd542cdd9c5c3ef745c9
    outputDockerImageReference: image-registry.openshift-image-registry.svc:5000/webproject/webapp-name:latest
    phase: Complete
    stages:
    - durationMilliseconds: 1218
      name: FetchInputs
      startTime: 2020-10-13T07:25:01Z
      steps:
      - durationMilliseconds: 1218
        name: FetchGitSource
        startTime: 2020-10-13T07:25:01Z
    - durationMilliseconds: 14339
      name: PullImages
      startTime: 2020-10-13T07:25:04Z
      steps:
      - durationMilliseconds: 14339
        name: PullBaseImage
        startTime: 2020-10-13T07:25:04Z
    - durationMilliseconds: 26251
      name: Build
      startTime: 2020-10-13T07:25:19Z
      steps:
      - durationMilliseconds: 26251
        name: DockerBuild
        startTime: 2020-10-13T07:25:19Z
    - durationMilliseconds: 4810
      name: PushImage
      startTime: 2020-10-13T07:25:45Z
      steps:
      - durationMilliseconds: 4810
        name: PushDockerImage
        startTime: 2020-10-13T07:25:45Z
    startTimestamp: 2020-10-13T07:24:53Z
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
