apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: https://github.com/msakhawat/FlaskApp.git
      deployment.kubernetes.io/revision: "2"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"webapp-name:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"webapp-name\")].image","pause":"false"}]'
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2020-10-13T07:24:52Z
    generation: 2
    labels:
      app: webapp-name
      app.kubernetes.io/component: webapp-name
      app.kubernetes.io/instance: webapp-name
      app.kubernetes.io/part-of: webapp-appname
    name: webapp-name
    namespace: webproject
    resourceVersion: "299590400"
    selfLink: /apis/apps/v1/namespaces/webproject/deployments/webapp-name
    uid: 35bd0bdc-fd42-4c5c-829f-c95258fec5c5
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: webapp-name
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: webapp-name
          deploymentconfig: webapp-name
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/webproject/webapp-name@sha256:616a75aca2298f3361558b4d8708093716e8289f3d4cfd542cdd9c5c3ef745c9
          imagePullPolicy: Always
          name: webapp-name
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2020-10-13T07:25:55Z
      lastUpdateTime: 2020-10-13T07:25:55Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2020-10-13T07:24:52Z
      lastUpdateTime: 2020-10-13T07:25:55Z
      message: ReplicaSet "webapp-name-5b7586d876" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
