apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: 2020-10-13T07:24:52Z
    labels:
      app: webapp-name
      app.kubernetes.io/component: webapp-name
      app.kubernetes.io/instance: webapp-name
      app.kubernetes.io/part-of: webapp-appname
    name: webapp-name
    namespace: webproject
    resourceVersion: "299588730"
    selfLink: /apis/route.openshift.io/v1/namespaces/webproject/routes/webapp-name
    uid: f7dd360c-b8e0-415c-bbb3-c61da750dcfb
  spec:
    host: webapp-name-webproject.apps.shared-na4.na4.openshift.opentlc.com
    port:
      targetPort: 5000-tcp
    to:
      kind: Service
      name: webapp-name
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2020-10-13T07:24:52Z
        status: "True"
        type: Admitted
      host: webapp-name-webproject.apps.shared-na4.na4.openshift.opentlc.com
      routerCanonicalHostname: apps.shared-na4.na4.openshift.opentlc.com
      routerName: default
      wildcardPolicy: None
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
